version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../deployment/railway.dockerfile
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=growth_signals
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - growth-signals-network

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - growth-signals-network

  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - growth-signals-network

volumes:
  mongodb_data:

networks:
  growth-signals-network:
    driver: bridge